### ISSUE TITLE
Hi, I just want to know where the I-SSIM loss is in your code?

### ISSUE THREAD

**Issue by Ssssssyz** [dk-liang/FIDTM#11]
I have not found the I-SSIM loss in the code, and I just find the nn.MSE loss in the code. So, I want to know where the I-SSIM loss is. Thanks!!!

**Comment by dk-liang** [comment]
Thanks for your attention! We now have not released the I-SSIM loss, and this project only contains the baseline code for training.  Of course, the baseline code also achieves excellent localization and counting performance. We will release the I-SSIM code when the review completed.
