### ISSUE TITLE
Too many False positives

### ISSUE THREAD

**Issue by RawanLaz** [dk-liang/FIDTM#12]
I tried to run the video demo code on a video and using the model mode_best_57.pth or the model model_best.pth I got so many false positives? what can I do to be able to run the model on other data? (note that I didn't scale down the frames in the video)
![Screenshot from 2021-05-20 16-48-19](https://user-images.githubusercontent.com/8888231/119000333-50ac6480-b98b-11eb-9596-d8e01daefc10.png)

**Comment by dk-liang** [comment]
Thanks for your attention! The model_best_57 is trained from ShanghaiTech PartA, a small crowd dataset. Maybe you can try to utilize the pre-trained model from the NWPU-Crowd dataset.  You can download the pre-trained model from https://1drv.ms/u/s!Ak_WZsh5Fl0lhCneubkIv1mTllAZ?e=0zMHSM. Additionally, sometimes change the test video's resolution is useful, do you try to test it based on 1920 x 1080 or 960 x 560?

**Comment by RawanLaz** [comment]
Thank you for your response! 
I tried the other model (ShanghaiTechB) and this is the output. The number of people in the image is around ~60 people but the counter shows 243 and The video resolution is 1280*720 
note that there are multiple overlapping boxes on the same person (should I use non maximum suppression?)

![Screenshot from 2021-05-22 14-08-41](https://user-images.githubusercontent.com/8888231/119225982-3dbe9f00-bb07-11eb-954b-e49464934bd8.png)

**Comment by dk-liang** [comment]
Hey, we sorry that we only uploaded the PartA and PartB pre-trained model in Onedrive in the past. We now have successful upload the other datasets’ pre-trained models in the Onedrive. Could you try to utilize the other model to test the video? Besides, I think NMS is out necessary, and you can change the LMDS code to suppress the false positive. Specifically, you can modify the threshold in "input[input < 100.0 / 255.0 * torch.max(input)] = 0”. The default threshold is set as 100.

**Comment by RawanLaz** [comment]
Wow! I tried the model "model_best_nwpu.pth" and it did REALLY well!! Thanks for sharing the other models! 
![Screenshot from 2021-05-23 16-53-31](https://user-images.githubusercontent.com/8888231/119265630-a8470c00-bbe7-11eb-9b49-8289e88ecb32.png)
