### ISSUE TITLE
It takes 24 hours to train 10 epoch, about 246,080 pictures, is there something wrong, or it does so?

### ISSUE THREAD

**Issue by YuYue26** [dk-liang/FIDTM#17]
parameter of the computer: 
GPU:1*1080Ti,  12GB

parameter of the train code:  
crop_size:128*128
batch_size:16

**Comment by dk-liang** [comment]
Hi, 
What dataset do you train?
Actually, I trained with a single GPU (2080TI), it takes about 20s for each epoch in the Part A dataset. Hence, I think it is impossible to only train 10 epochs with 24 hours, even in 1080TI.

**Comment by YuYue26** [comment]
The dataset names DroneCrowd, which contain 24,600 pictures in the train dataset. I think it's difficult to train this datasets with HRNet, it takes me a long time!
 					
 				
 			
 		





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月23日(星期三) 下午5:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dk-liang/FIDTM] It takes 24 hours to train 10 epoch, about 246,080 pictures, is there something wrong, or it does so? (#17)



Hi,
 What dataset do you train?
 Actually, I trained with a single GPU (2080TI), it takes about 20s for each epoch in the Part A dataset. Hence, I think it is impossible to only train 10 epochs with 24 hours, even in 1080TI.

**Comment by dk-liang** [comment]
This is a huge dataset. I think you can try to utilize the VGG16 as the backbone.
