### ISSUE TITLE
About the training data set

### ISSUE THREAD

**Issue by neversettle-tech** [dk-liang/FIDTM#20]
My current data set is only marked with head bounding boxes. Can I take the center point of the head bounding box as the training set for your model?  Consider this scenario：Bounding box A is partially covered by bounding box B. When the center point of bounding box A is taken, the center point is likely to fall on the head of the person inside bounding box B. Does this affect the training？
I look forward to your reply. Thank you

**Comment by dk-liang** [comment]
Using the box centres as ground truth can be trained in our method, and it will not affect the training.

**Comment by BoltenWang-Meta** [comment]
I think there will be a redundant annotation of the outer head. Because the net fits on head only, the hidden head couldn' t be the training samples. However, if this hidden head can be predicted depends on the robustness of the net.
