### ISSUE TITLE
about "the txt file in './local_eval/point_files/',"

### ISSUE THREAD

**Issue by 1900lxl** [dk-liang/FIDTM#21]
how can we get the "xxxxx_gt.txt"? 
such as "A_gt.txt" and "B_gt.txt ".

thanks!

**Comment by dk-liang** [comment]
> how can we get the "xxxxx_gt.txt"?
> such as "A_gt.txt" and "B_gt.txt ".
> 
> thanks!

See ./local_eval/gt_generate.py

**Comment by 1900lxl** [comment]
@dk-liang thanks for your help!
