### ISSUE TITLE
loss

### ISSUE THREAD

**Issue by neversettle-tech** [dk-liang/FIDTM#24]
Is there only MSE Loss in the code, but no ISMM Loss？
Will it affect my training？

**Comment by dk-liang** [comment]
No, it can train with MSE loss.

**Comment by neversettle-tech** [comment]
However, using only one Loss let me feel that the training effect is not very good.
Can you upload the complete code？

**Comment by dk-liang** [comment]
> However, using only one Loss let me feel that the training effect is not very good.
> Can you upload the complete code？

This work is under review, we will release the code when the review is completed.

**Comment by neversettle-tech** [comment]
So, when will it be released？

**Comment by neversettle-tech** [comment]
When will the code finish the reviewed?

**Comment by dk-liang** [comment]
> When will the code finish the reviewed?

Depending on the reviewers.

**Comment by dk-liang** [comment]
The paper is under review instead of the code.
