### ISSUE TITLE
Code of data preparation for nwpu dataset not provided

### ISSUE THREAD

**Issue by svshivapuja** [dk-liang/FIDTM#26]
Code of data preparation for nwpu dataset not provided at the link [```data```](https://github.com/dk-liang/FIDTM/tree/master/data) @RawanLaz @dk-liang @ZeeRizvee

**Comment by blue-q** [comment]
Excuse me, do you know how to deal with nwpu dataset now

**Comment by dk-liang** [comment]
please refer to CLTR (https://github.com/dk-liang/CLTR)
