### ISSUE TITLE
I-SSIM Loss

### ISSUE THREAD

**Issue by BoltenWang-Meta** [dk-liang/FIDTM#27]
Sorry, i didn' t find your implementation of  I-SSIM loss.

**Comment by feixuedudiao** [comment]
the same too.

**Comment by njupt-lpc** [comment]
you need completion by yourself

**Comment by dk-liang** [comment]
Sorry, after discussing with my coauthors, we can not release the I-SSIM  as soon as possible before this work is formally published.  Actually, the performance of the baseline can also be further improved by using some existing tricks.

**Comment by rydenisbak** [comment]
I did implement I-SSIM and add some useful tricks, I can publish it in my fork, if someone needs it.
I got 55.86 MAE instead of 57.0 from paper on SHA dataset.

**Comment by mariosconsta** [comment]
> I did implement I-SSIM and add some useful tricks, I can publish it in my fork, if someone needs it. I got 55.86 MAE instead of 57.0 from paper on SHA dataset.

If the authors allow it I would like to see the implementation of I-SSIM for personal usage.

**Comment by rydenisbak** [comment]
@mariosconsta hello
Type of license of the code allows me be free to modify and publish code, so I will publish in couple days, because now i have some important deadline in my job

**Comment by mariosconsta** [comment]
@rydenisbak Hey man, I hope you are doing great. Just checking if you had the time to update your fork with the implementation.

**Comment by Gananathan** [comment]
> @mariosconsta hello Type of license of the code allows me be free to modify and publish code, so I will publish in couple days, because now i have some important deadline in my job

Hey @rydenisbak, is there any update on publishing of the loss function module you have implemented. Thank you in advance.

**Comment by Thepang25** [comment]
Hey. @rydenisbak I noticed that the author's paper has been successfully published, when can you update your duplicate I-SSIM loss

**Comment by Thepang25** [comment]
Hi,@rydenisbak 
I noticed that the author's paper has been successfully published, when can you update your reproduced I-SSIM loss.
I have followed your Home page, and I really need your fantastic work!
Thank you in advance.

**Comment by rydenisbak** [comment]
excuse me guys @mariosconsta @Gananathan @Thepang25  for looooong waiting, 

I published my implementation, now you can check it out
https://github.com/rydenisbak/FIDTM/tree/visionlabs_implement

**Comment by rydenisbak** [comment]
@dk-liang should I create PR ? May be you create new branch for this PR? Now I can do PR only to master branch
