### ISSUE TITLE
模型在训练时损失很大

### ISSUE THREAD

**Issue by waric01** [dk-liang/FIDTM#28]
老师，您好！我在使用你的模型训练时，发现损失很大，第一轮loss高达几十万，随着训练轮次增加，loss依然好几千，请问一下是什么原因呢，谢谢！
![1](https://user-images.githubusercontent.com/103834525/165293666-52d36e5a-d9ab-4bdb-8d04-57e4e0361bc3.png)

**Comment by dk-liang** [comment]
你好，这是正常现象，因为我算的loss是pixel层面的MSE loss，用的是sum，不是mean

**Comment by waric01** [comment]
好的，非常感谢老师您在百忙中抽时间解答，十分感激和感谢！
