### ISSUE TITLE
HRNet vs. VGG-16

### ISSUE THREAD

**Issue by pietz** [dk-liang/FIDTM#29]
Thanks for your work and sharing the code. It seems like for all your experiments you're using the HRNet architecture, which is a much more advanced model compared to VGG-16 that is used in most other works. From my perspective it's hard to judge how much improvement comes from the loss function you introduce and how much comes from the backbone alone.

What are your thoughts on this? Did you also run experiments with a VGG-16 backbone?

Thanks,
Paul

**Comment by dk-liang** [comment]
Yes, please see the latest version
