### ISSUE TITLE
视频测试出现问题

### ISSUE THREAD

**Issue by springs826911679** [dk-liang/FIDTM#30]
您好，我在测试您给的视频数据时出现异常。
![demo](https://user-images.githubusercontent.com/73974896/179459778-8ce9acc8-edc6-4060-9831-d3ab2a2c004e.jpg)

**Comment by dk-liang** [comment]
应该是模型参数没有成功load

**Comment by springs826911679** [comment]
谢谢您的回复，但我调试时代码没有发生错误提示，而模型预测时出现问题

**Comment by dk-liang** [comment]
> 谢谢您的回复，但我调试时代码没有发生错误提示，而模型预测时出现问题

即便没有load模型，也不会报错，这个问题应该是你没有load预训练的模型
