### ISSUE TITLE
Training on custom dataset

### ISSUE THREAD

**Issue by mariosconsta** [dk-liang/FIDTM#37]
Hello

If I want to train this model on my own custom dataset, I just need to change the files _**fidt_generate_xx.py**_, _**make_npydata.py**_ and _**train_baseline.py**_?

Also, my dataset contains bounding boxes, but that shouldn't be a big issue right?

**Comment by dk-liang** [comment]
Yes, you are right

**Comment by mariosconsta** [comment]
> Yes, you are right

Thank you for the swift response. I am trying to solve the low performance on crowd localization where the view is top-down from a drone. Since it's top down, only the heads are visible as blobs, and I think if I train it on some of my data which is only top-down, it might increase its performance.

**Comment by luduangit** [comment]
Hello, I also plan to train on a custom dataset. How can I generate a mat file like the one in ShanghaiTech dataset? Is training necessary? I roughly looked at the code and it seems like it is necessary to use it. Thank you for helping me answer this question.
