### ISSUE TITLE
ISSIM-Loss

### ISSUE THREAD

**Issue by rydenisbak** [dk-liang/FIDTM#40]
Hello @dk-liang, thank you for the great work.

Can you provide ISSIM Loss validation value for the last epoch for SHA dataset?
I can do normalization the loss by several ways, knowledge about your validation value helps me choose the right one.
And I will know your loss balance between MSE and ISSIM.

**Comment by mariosconsta** [comment]
Hey @rydenisbak, how do you handle the huge range of value difference between MSE and SSIM? MSE ranges in the hundreds and SSIM ranges between 0 and 1.

`SSIM Loss: 0.96907794 - MSE Loss: 1452.20227051 - Loss: 1453.17138672`

So I suspect that the model will try to minimize based on MSE only?
