### ISSUE TITLE
Tracking not working as expected

### ISSUE THREAD

**Issue by firdauskotp** [dk-liang/FIDTM#50]
Hello, I face an issue with the tracking through the video_demo.py

I trained the ShanghaiTech dataset only and got this result when training the video:

![Capture](https://github.com/dk-liang/FIDTM/assets/46307489/c5632ac6-14ef-4fdc-9baa-05a9157b76a3)

May I have advice on this? Is it due to me not training the other datasets?

**Comment by dk-liang** [comment]
You can first try it with the pre-training weights I provided

**Comment by firdauskotp** [comment]
Alright, will try and let you know. Thank you for the swift response ^_^

**Comment by firdauskotp** [comment]
hello, apologies for the super late reply. I tried it with the pre-training weights (the one at the bottom where I need to edit the config.py) but the tracking still happen like in the picture

**Comment by firdauskotp** [comment]
Hello, when I use the pretraining model it says that there is a state_dict error

Can you pass me the link for the pretraining weights mentioned because I may have used the wrong model

**Comment by firdauskotp** [comment]
It's okay, I solved it. Found from the previous issue that it is better to use the nwpu pretrained model for denser crowds. Got the link from here:

https://onedrive.live.com/?id=255D1679C866D64F%21553&cid=255D1679C866D64F&redeem=aHR0cHM6Ly8xZHJ2Lm1zL3UvcyFBa19XWnNoNUZsMGxoQ25ldWJrSXYxbVRsbEFaP2U9MHpNSFNN

Thank you ^_^
