### ISSUE TITLE
Unable to download the model files from Baidu

### ISSUE THREAD

**Issue by wolframalpha** [dk-liang/FIDTM#8]
First, thanks for the amazing work. I cannot download the model files from Baidu since I am from outside China (cannot even sign-up it's all Chinese even after google translate).
Could you please upload the model files on Google Drive or share a direct link to download them.

Thanks !

**Comment by dk-liang** [comment]
Thanks for your attention! We now provided the Onedrive download link (https://1drv.ms/u/s!Ak_WZsh5Fl0lhCneubkIv1mTllAZ?e=0zMHSM).
